[rigel]
command=rigel -a "%(ENV_GM_ALGO)s" --coin "%(ENV_GM_COIN)s" -o "%(ENV_GM_SERV)s":"%(ENV_GM_PORT)s" -u "%(ENV_GM_USER)s" -w my_rig --log-file /var/log/rigel.log
autostart=true
autorestart=unexpected
exitcodes = 0
startsecs = 3
stderr_logfile=/var/log/rigel.err.log
stdout_logfile=/var/log/rigel.out.log
