[xmrig]
command=xmrig --url "startum+tcp://%(ENV_XMR_SERV)s:%(ENV_XMR_PORT)s" --algo="%(ENV_XMR_ALGO)s" --user "%(ENV_XMR_USER)s"
autostart=true
autorestart=unexpected
exitcodes = 0,1
startsecs = 3
stderr_logfile=/var/log/xmrig.err.log
stdout_logfile=/var/log/xmrig.out.log
