name: Docker Image CI

on:
  workflow_dispatch:

  schedule:
  - cron: '0 4 * * 1'

permissions:
  actions:  write
  contents: read
  packages: write

jobs:
  Build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        UBUNTU_VERSION:
        - 24.04
        - 22.04
        include:
        - CUDA_VERSION_MAJOR: 12.9
          CUDA_VERSION_MINOR: 12.9.1
        - CUDA_VERSION_MAJOR: 12.8
          CUDA_VERSION_MINOR: 12.8.1
        - CUDA_VERSION_MAJOR: 12.6
          CUDA_VERSION_MINOR: 12.6.3
        - CUDA_VERSION_MAJOR: 12.5
          CUDA_VERSION_MINOR: 12.5.1
        - CUDA_VERSION_MAJOR: 12.4
          CUDA_VERSION_MINOR: 12.4.1
        - CUDA_VERSION_MAJOR: 12.3
          CUDA_VERSION_MINOR: 12.3.2
        - CUDA_VERSION_MAJOR: 12.2
          CUDA_VERSION_MINOR: 12.2.2
        - CUDA_VERSION_MAJOR: 12.1
          CUDA_VERSION_MINOR: 12.1.1
        - CUDA_VERSION_MAJOR: 12.0
          CUDA_VERSION_MINOR: 12.0.1
        - CUDA_VERSION_MAJOR: 11.8
          CUDA_VERSION_MINOR: 11.8.0
        - CUDA_VERSION_MAJOR: 11.7
          CUDA_VERSION_MINOR: 11.7.1
        - CUDA_VERSION_MAJOR: 11.6
          CUDA_VERSION_MINOR: 11.6.2
        - CUDA_VERSION_MAJOR: 11.5
          CUDA_VERSION_MINOR: 11.5.2
        - CUDA_VERSION_MAJOR: 11.3
          CUDA_VERSION_MINOR: 11.3.1
        - CUDA_VERSION_MAJOR: 11.1
          CUDA_VERSION_MINOR: 11.1.1
        - CUDA_VERSION_MAJOR: 11.0
          CUDA_VERSION_MINOR: 11.0.3
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        image: ghcr.io/amitie10g/binfmt:latest
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=ghcr.io/amitie10g/buildkit:master
    - name: Set tags metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/miner
        tags: |
          ${{ matrix.CUDA_VERSION_MAJOR }}-${{ matrix.UBUNTU_VERSION }}
          ${{ matrix.CUDA_VERSION_MINOR }}-${{ matrix.UBUNTU_VERSION }}
          ${{ strategy.job-index == 0 && 'latest' || '' }}
    - name: Build And Push Docker Image
      uses: docker/build-push-action@v5
      id: build
      with:
        push: true
        context: .
        build-args: |
          UBUNTU_VERSION=${{ matrix.UBUNTU_VERSION }}
          CUDA_VERSION=${{ matrix.CUDA_VERSION_MINOR }}
        cache-to: type=inline
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
